apiVersion: v1    # This is the API version        
kind: Pod   # This is the kind of resource   
metadata:   # This is the metadata of the resource
  name: nginx   # This is the name of the pod
  namespace: nginx        # This is the namespace where the pod will be created
spec:   # This is the specification of the pod 
  containers:     # This is the list of containers in the pod 
  - name: nginx     # This is the name of the container 
    image: nginx:1.14.2     # This is the image of the container
    ports:          # This is the list of ports that the container will expose 
    - containerPort: 80   # This is the port that the container will expose 
